"""
Process JSONL data generated by MediaCrawler
Parse post information and download images
"""

import json
import httpx
from pathlib import Path


def parse_jsonl_and_download(jsonl_file: str, save_dir: str = "downloads"):
    """
    Parse JSONL file and download images

    Args:
        jsonl_file: JSONL file path
        save_dir: Image save directory
    """
    save_path = Path(save_dir)
    save_path.mkdir(exist_ok=True)

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://www.xiaohongshu.com/"
    }

    print(f"Reading file: {jsonl_file}\n")

    with open(jsonl_file, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            # Parse each line of JSON
            post = json.loads(line.strip())

            note_id = post.get("note_id")
            title = post.get("title", "No Title")
            desc = post.get("desc", "")
            liked_count = post.get("liked_count", "0")
            collected_count = post.get("collected_count", "0")
            comment_count = post.get("comment_count", "0")

            # Image list is comma-separated string
            image_list_str = post.get("image_list", "")
            image_urls = [url.strip() for url in image_list_str.split(",") if url.strip()]

            print(f"{'='*60}")
            print(f"Post #{line_num}")
            print(f"{'='*60}")
            print(f"ID: {note_id}")
            print(f"Title: {title}")
            print(f"Content: {desc[:100]}{'...' if len(desc) > 100 else ''}")
            print(f"Likes: {liked_count} | Saved: {collected_count} | Comments: {comment_count}")
            print(f"Image count: {len(image_urls)}")
            print()

            # Create post-specific directory
            if image_urls:
                note_dir = save_path / note_id
                note_dir.mkdir(exist_ok=True)

                # Save post info to text file
                info_file = note_dir / "info.txt"
                with open(info_file, 'w', encoding='utf-8') as info_f:
                    info_f.write(f"Title: {title}\n")
                    info_f.write(f"Content:\n{desc}\n\n")
                    info_f.write(f"Likes: {liked_count}\n")
                    info_f.write(f"Saved: {collected_count}\n")
                    info_f.write(f"Comments: {comment_count}\n")
                    info_f.write(f"Link: {post.get('note_url', '')}\n")

                print(f"Starting download of {len(image_urls)} images...")

                # Download images
                with httpx.Client(headers=headers, timeout=30.0, follow_redirects=True) as client:
                    for i, img_url in enumerate(image_urls, 1):
                        try:
                            print(f"  [{i}/{len(image_urls)}] Downloading...", end=" ")
                            resp = client.get(img_url)
                            resp.raise_for_status()

                            # Save image
                            file_path = note_dir / f"{note_id}_{i}.jpg"
                            with open(file_path, "wb") as img_f:
                                img_f.write(resp.content)

                            print(f"✓ Saved: {file_path}")

                        except Exception as e:
                            print(f"✗ Failed: {e}")

                print(f"\nPost {note_id} processing complete!")
                print(f"Saved to: {note_dir}")
                print()

    print(f"\n{'='*60}")
    print(f"All processing complete! Images saved in: {save_path}")
    print(f"{'='*60}")


if __name__ == "__main__":
    # Path to data file generated by MediaCrawler
    jsonl_file = "MediaCrawler/data/xhs/jsonl/detail_contents_2026-03-18.jsonl"

    # Start processing
    parse_jsonl_and_download(jsonl_file, save_dir="downloads")
