"""
RedNote Post Crawler Tool
Extract post title, content, and images from sharing links
"""

import re
import json
import os
from pathlib import Path
from typing import Dict, List, Optional
import httpx
from urllib.parse import urlparse, parse_qs


class XHSPostCrawler:
    """RedNote Post Crawler"""

    def __init__(self, save_dir: str = "downloads"):
        self.save_dir = Path(save_dir)
        self.save_dir.mkdir(exist_ok=True)

        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Referer": "https://www.xiaohongshu.com/"
        }

    def extract_note_id(self, share_url: str) -> Optional[str]:
        """
        Extract note_id from sharing link
        Supported formats:
        - https://www.xiaohongshu.com/explore/65f...
        - https://xhslink.com/xxx
        - Direct note_id
        """
        # If it's a full URL
        if share_url.startswith('http'):
            # Match ID after /explore/
            match = re.search(r'/explore/([a-f0-9]+)', share_url)
            if match:
                return match.group(1)

            # Match ID after /discovery/item/
            match = re.search(r'/discovery/item/([a-f0-9]+)', share_url)
            if match:
                return match.group(1)

        # If it's already in note_id format
        if re.match(r'^[a-f0-9]{24}$', share_url):
            return share_url

        return None

    def fetch_post_info(self, share_url: str) -> Dict:
        """
        Get post information

        Note: This method uses simple HTTP requests, which may be blocked by anti-crawling
        Recommended to use MediaCrawler with browser automation for more stable results
        """
        note_id = self.extract_note_id(share_url)
        if not note_id:
            raise ValueError(f"Cannot extract note_id from URL: {share_url}")

        print(f"Extracted note_id: {note_id}")

        # Return reminder info because direct HTTP requests may be blocked
        return {
            "note_id": note_id,
            "url": share_url,
            "message": "Recommend using MediaCrawler tool to get complete data",
            "instruction": "Please refer to fetch_with_mediacrawler() method"
        }

    def download_images(self, image_urls: List[str], note_id: str) -> List[str]:
        """Download images to local"""
        downloaded_files = []

        note_dir = self.save_dir / note_id
        note_dir.mkdir(exist_ok=True)

        with httpx.Client(headers=self.headers, timeout=30.0, follow_redirects=True) as client:
            for i, img_url in enumerate(image_urls):
                try:
                    print(f"Downloading image {i+1}/{len(image_urls)}...")
                    resp = client.get(img_url)
                    resp.raise_for_status()

                    # Save image
                    ext = "jpg"
                    file_path = note_dir / f"{note_id}_{i+1}.{ext}"

                    with open(file_path, "wb") as f:
                        f.write(resp.content)

                    downloaded_files.append(str(file_path))
                    print(f"  ✓ Saved: {file_path}")

                except Exception as e:
                    print(f"  ✗ Download failed {img_url}: {e}")

        return downloaded_files

    def parse_mediacrawler_json(self, json_file_path: str) -> List[Dict]:
        """
        Parse JSON file generated by MediaCrawler
        Get post title, content, and image list
        """
        with open(json_file_path, 'r', encoding='utf-8') as f:
            notes = json.load(f)

        parsed_posts = []

        for note in notes:
            post_info = {
                "note_id": note.get("note_id"),
                "title": note.get("title", ""),
                "desc": note.get("desc", ""),  # Content
                "type": note.get("type", ""),  # normal/video
                "liked_count": note.get("liked_count", 0),
                "collected_count": note.get("collected_count", 0),
                "comment_count": note.get("comment_count", 0),
                "share_count": note.get("share_count", 0),
                "image_list": [],
                "video_url": note.get("video_url", "")
            }

            # Extract image URLs
            images = note.get("image_list", [])
            for img_info in images:
                # Prefer original image URL
                img_url = img_info.get("url") or img_info.get("url_default") or img_info.get("url_pre")
                if img_url:
                    post_info["image_list"].append(img_url)

            parsed_posts.append(post_info)

        return parsed_posts

    def fetch_with_mediacrawler(self, share_url: str) -> str:
        """
        Instructions for using MediaCrawler to get post information

        Returns configuration and run steps
        """
        note_id = self.extract_note_id(share_url)

        instructions = f"""
========================================
Using MediaCrawler to Get RedNote Post Info
========================================

Step 1: Install MediaCrawler
--------------------------
git clone https://github.com/NanmiCoder/MediaCrawler.git
cd MediaCrawler
uv sync
uv run playwright install chromium

Step 2: Configure Target URL
--------------------------
Edit config/xhs_config.py, add:

XHS_SPECIFIED_NOTE_URL_LIST = [
    "{share_url}"
]

Step 3: Run Crawler
--------------------------
uv run main.py --platform xhs --lt qrcode --type detail

After scanning QR code to login, data will be saved to data/xhs/ directory

Step 4: Parse and Download
--------------------------
Use this script to parse JSON and download images:

from xhs_crawler import XHSPostCrawler

crawler = XHSPostCrawler()
posts = crawler.parse_mediacrawler_json("data/xhs/json/notes_xxx.json")

for post in posts:
    print(f"Title: {{post['title']}}")
    print(f"Content: {{post['desc']}}")
    print(f"Image count: {{len(post['image_list'])}}")

    # Download images
    if post['image_list']:
        crawler.download_images(post['image_list'], post['note_id'])

========================================
Extracted note_id: {note_id}
========================================
"""
        return instructions


def main():
    """Main function example"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python xhs_crawler.py <RedNote sharing link>")
        print("\nExamples:")
        print("  python xhs_crawler.py 'https://www.xiaohongshu.com/explore/65f...'")
        print("  python xhs_crawler.py '65f1234567890abcdef12345'")
        return

    share_url = sys.argv[1]

    crawler = XHSPostCrawler()

    # Display complete instructions for using MediaCrawler
    instructions = crawler.fetch_with_mediacrawler(share_url)
    print(instructions)

    # If you already have MediaCrawler generated data file, use it like this:
    # posts = crawler.parse_mediacrawler_json("data/xhs/json/notes_2024-xx-xx.json")
    # for post in posts:
    #     print(f"\nTitle: {post['title']}")
    #     print(f"Content: {post['desc'][:100]}...")
    #     if post['image_list']:
    #         crawler.download_images(post['image_list'], post['note_id'])


if __name__ == "__main__":
    main()